[versions]

shadowVer = "8.1.1"
gitVer = "3.1.3"
kotlinVer = "1.9.22"

[plugins]

shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadowVer" }
git = { id = "net.kyori.indra.git", version.ref = "gitVer" }